import { NavLinksModel } from '../models/NavLinksModel';
import { UserTypeConstant } from './UserTypeConstant';

export const NavItemsContant: NavLinksModel[] = [
  // {
  //   label: 'Dashboard',
  //   roles: [
  //     UserTypeConstant.ADMIN,
  //     UserTypeConstant.CUSTOMER,
  //     UserTypeConstant.CUSTOMER_USER,
  //     UserTypeConstant.PROFESSIONAL,
  //   ],
  //   category: '',
  //   subItems: [],
  //   icon: 'home',
  //   url: '/',
  // },
  {
    label: 'Dashboard',
    roles: [
      UserTypeConstant.ADMIN,
      UserTypeConstant.CUSTOMER,
      UserTypeConstant.CUSTOMER_USER,
      UserTypeConstant.PROFESSIONAL,
    ],
    category: '',
    subItems: [],
    icon: 'home',
    url: '',
  },
  {
    label: 'Vehicle In/out',
    roles: [
      UserTypeConstant.ADMIN,
      UserTypeConstant.CUSTOMER,
      UserTypeConstant.CUSTOMER_USER,
    ],
    category: '',
    subItems: [
      {
        label: 'View',
        roles: [
          UserTypeConstant.ADMIN,
          UserTypeConstant.CUSTOMER,
          UserTypeConstant.CUSTOMER_USER,
        ],
        icon: '',
        url: '/assignments',
        category: '',
        subItems: [],
      },
      {
        label: 'Add',
        roles: [
          UserTypeConstant.ADMIN,
          UserTypeConstant.CUSTOMER,
          UserTypeConstant.CUSTOMER_USER,
        ],
        icon: '',
        url: '/assignments/add',
        category: '',
        subItems: [],
      },
    ],
    icon: 'compare_arrows',
    url: '/',
  },
  {
    label: 'Pre-request For vehicle',
    roles: [
      UserTypeConstant.ADMIN,
      UserTypeConstant.CUSTOMER,
      UserTypeConstant.CUSTOMER_USER,
    ],
    category: '',
    subItems: [
      {
        label: 'View',
        roles: [
          UserTypeConstant.ADMIN,
          UserTypeConstant.CUSTOMER,
          UserTypeConstant.CUSTOMER_USER,
        ],
        icon: '',
        url: '/assignments',
        category: '',
        subItems: [],
      },
      {
        label: 'Add',
        roles: [
          UserTypeConstant.ADMIN,
          UserTypeConstant.CUSTOMER,
          UserTypeConstant.CUSTOMER_USER,
        ],
        icon: '',
        url: '/assignments/add',
        category: '',
        subItems: [],
      },
    ],
    icon: 'assignment',
    url: '/',
  },
  {
    label: 'Vehicle Tracking',
    roles: [
      UserTypeConstant.ADMIN,
      UserTypeConstant.CUSTOMER,
      UserTypeConstant.CUSTOMER_USER,
    ],
    category: '',
    subItems: [
      {
        label: 'Live Tracking',
        roles: [
          UserTypeConstant.ADMIN,
          UserTypeConstant.CUSTOMER,
          UserTypeConstant.CUSTOMER_USER,
        ],
        subItems: [],
        category: '',
        icon: '',
        url: ''
      },
      {
        label: 'Parked Vehicles',
        roles: [
          UserTypeConstant.ADMIN,
          UserTypeConstant.CUSTOMER,
          UserTypeConstant.CUSTOMER_USER,
        ],
        subItems: [],
        category: '',
        icon: '',
        url: ''
      },
    ],
    icon: 'location_on',
    url: '/',
  },
  {
    label: 'Fuel/Imprest A/C',
    roles: [
      UserTypeConstant.ADMIN,
      UserTypeConstant.CUSTOMER,
      UserTypeConstant.CUSTOMER_USER,
    ],
    category: '',
    subItems: [
      {
        label: 'Fuel Refilling',
        roles: [
          UserTypeConstant.ADMIN,
          UserTypeConstant.CUSTOMER,
          UserTypeConstant.CUSTOMER_USER,
        ],
        icon: '',
        url: '/patients',
        category: '',
        subItems: [],
      },
      {
        label: 'Imprest A/C',
        roles: [
          UserTypeConstant.ADMIN,
          UserTypeConstant.CUSTOMER,
          UserTypeConstant.CUSTOMER_USER,
        ],
        icon: '',
        url: '/patients/imprest',
        category: '',
        subItems: [],
      },
    ],
    icon: 'invert_colors',
    url: '/',
  },
  {
    label: 'Vehicle Management',
    roles: [
      UserTypeConstant.ADMIN,
      UserTypeConstant.CUSTOMER_USER,
      UserTypeConstant.CUSTOMER,
      UserTypeConstant.PROFESSIONAL,
    ],
    category: '',
    subItems: [
      {
        label: 'All Vehicles',
        roles: [
          UserTypeConstant.ADMIN,
          UserTypeConstant.CUSTOMER,
          UserTypeConstant.CUSTOMER_USER,
          UserTypeConstant.PROFESSIONAL,
        ],
        icon: '',
        url: 'medical-team',
        category: '',
        subItems: [],
      },
      {
        label: 'Add Vehicle',
        roles: [
          UserTypeConstant.ADMIN,
          UserTypeConstant.CUSTOMER,
          UserTypeConstant.CUSTOMER_USER,
        ],
        icon: '',
        url: '/medical-team/add',
        category: '',
        subItems: [],
      },
      {
        label: 'Spare-Part/Accessories',
        roles: [
          UserTypeConstant.ADMIN,
          UserTypeConstant.CUSTOMER,
          UserTypeConstant.CUSTOMER_USER,
          UserTypeConstant.PROFESSIONAL,
        ],
        icon: '',
        url: 'medical-team',
        category: '',
        subItems: [],
      },
      {
        label: 'Insurance/Pollution',
        roles: [
          UserTypeConstant.ADMIN,
          UserTypeConstant.CUSTOMER,
          UserTypeConstant.CUSTOMER_USER,
          UserTypeConstant.PROFESSIONAL,
        ],
        icon: '',
        url: 'medical-team',
        category: '',
        subItems: [],
      },
    ],
    icon: 'directions_car',
    url: '/',
  },
  {
    label: 'Driver/Sewadar',
    roles: [UserTypeConstant.ADMIN],
    category: '',
    subItems: [
      {
        label: 'All Drivers',
        roles: [UserTypeConstant.ADMIN],
        icon: '',
        url: '/customer',
        category: '',
        subItems: [],
      },
      {
        label: 'Add Drivers',
        roles: [UserTypeConstant.ADMIN],
        icon: '',
        url: '/customer/add',
        category: '',
        subItems: [],
      },
    ],
    icon: 'people',
    url: '/',
  },

  // {
  //   label: 'Driver',
  //   roles: [UserTypeConstant.ADMIN, UserTypeConstant.CUSTOMER],
  //   category: '',
  //   subItems: [
  //     {
  //       label: 'All Drivers',
  //       roles: [UserTypeConstant.ADMIN, UserTypeConstant.CUSTOMER],
  //       category: '',
  //       subItems: [],
  //       icon: '',
  //       url: '/driver',
  //     },
  //     {
  //       label: 'Add Driver',
  //       roles: [UserTypeConstant.ADMIN, UserTypeConstant.CUSTOMER],
  //       category: '',
  //       subItems: [],
  //       icon: '',
  //       url: '/driver/add',
  //     },
  //   ],
  //   icon: 'local_taxi',
  //   url: '',
  // },
  // {
  //   label: 'Chat',
  //   roles: [
  //     UserTypeConstant.ADMIN,
  //     UserTypeConstant.CUSTOMER,
  //     UserTypeConstant.PROFESSIONAL,
  //   ],
  //   category: '',
  //   subItems: [],
  //   icon: 'chat',
  //   url: '/chat',
  // },
  // {
  //   label: 'Manage Activities #',
  //   roles: [
  //     UserTypeConstant.ADMIN
  //   ],
  //   category: '',
  //   subItems: [],
  //   icon: 'task alt',
  //   url: '/',
  // },

  // {
  //   label: 'Board',
  //   roles: [
  //     UserTypeConstant.ADMIN,
  //     UserTypeConstant.CUSTOMER,
  //     UserTypeConstant.CUSTOMER_USER,
  //   ],
  //   category: 'directory',
  //   subItems: [],
  //   icon: 'group',
  //   url: '/team-board',
  // },
  // {
  //   label: 'Ambulance',
  //   roles: [UserTypeConstant.ADMIN, UserTypeConstant.CUSTOMER],
  //   category: 'directory',
  //   subItems: [
  //     {
  //       label: 'All Medtrans Bookings',
  //       roles: [UserTypeConstant.ADMIN, UserTypeConstant.CUSTOMER],
  //       category: 'directory',
  //       subItems: [],
  //       icon: '',
  //       url: '/ambulance',
  //     },
  //     {
  //       label: 'Add Medtrans Booking',
  //       roles: [UserTypeConstant.ADMIN, UserTypeConstant.CUSTOMER],
  //       category: 'directory',
  //       subItems: [],
  //       icon: '',
  //       url: '/ambulance/add',
  //     },
  //   ],
  //   icon: 'local_car_wash',
  //   url: '/',
  // },
  // {
  //   label: 'Living',
  //   roles: [UserTypeConstant.ADMIN, UserTypeConstant.CUSTOMER],
  //   category: 'directory',
  //   subItems: [
  //     {
  //       label: 'All Livings',
  //       roles: [UserTypeConstant.ADMIN, UserTypeConstant.CUSTOMER],
  //       category: 'directory',
  //       subItems: [],
  //       icon: '',
  //       url: '/living',
  //     },
  //     {
  //       label: 'Add Living',
  //       roles: [UserTypeConstant.ADMIN, UserTypeConstant.CUSTOMER],
  //       category: 'directory',
  //       subItems: [],
  //       icon: '',
  //       url: '/living/add',
  //     },
  //   ],
  //   icon: 'local_car_wash',
  //   url: '/',
  // },
  // {
  //   label: 'Living Board',
  //   roles: [UserTypeConstant.ADMIN, UserTypeConstant.CUSTOMER],
  //   category: 'directory',
  //   subItems: [],
  //   icon: 'home',
  //   url: '/living/board',
  // },
  // {
  //   label: 'Job-Portal',
  //   roles: [UserTypeConstant.PROFESSIONAL],
  //   category: 'directory',
  //   subItems: [],
  //   icon: 'directory',
  //   url: '/job-portal',
  // },
  // {
  //   label: 'Job-Portal',
  //   roles: [UserTypeConstant.ADMIN, UserTypeConstant.CUSTOMER],
  //   category: 'directory',
  //   subItems: [
  //     {
  //       label: 'All Job Openings',
  //       roles: [UserTypeConstant.ADMIN, UserTypeConstant.CUSTOMER],
  //       category: 'directory',
  //       subItems: [],
  //       icon: '',
  //       url: '/job-portal',
  //     },
  //     {
  //       label: 'Add Job Opening',
  //       roles: [UserTypeConstant.ADMIN, UserTypeConstant.CUSTOMER],
  //       category: 'directory',
  //       subItems: [],
  //       icon: '',
  //       url: '/job-portal/add',
  //     },
  //   ],
  //   icon: 'work',
  //   url: '',
  // },
];
